prettier & cspell front side

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,22 +1,22 @@
 #!/bin/sh
 
-# Check code lint
-echo "Checking code lint..."
+# Check code lint & code spell (backend side)
+echo "Checking code lint and code spell..."
 (cd backend && pnpm lint)
 LINT_RESULT=$?
 
 if [ $LINT_RESULT -ne 0 ]; then
-  echo "Code formatting issues found. Commit aborted."
+  echo "Code formatting issues found (backend). Commit aborted."
   exit 1
 fi
 
-# Run codespell
-echo "Checking codespell..."
-(cd backend && pnpm cspell)
-CSPELL_RESULT=$?
+# Check code lint (frontend side)
+echo "Checking code lint and code spell..."
+(cd frontend && pnpm lint)
+LINT_RESULT=$?
 
-if [ $CSPELL_RESULT -ne 0 ]; then
-  echo "Code spell issues found. Commit aborted."
+if [ $LINT_RESULT -ne 0 ]; then
+  echo "Code formatting issues found (frontend). Commit aborted."
   exit 1
 fi
 
